# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias ..='cd ..'
#alias 4 8 15 16 23 42="reload"
alias bomb='echo ${bashForkBomb}'
alias c='clear'
alias check-log='sudo cat /var/log/auth.log | grep fail'
alias cp='cp -r'
alias df='df -h'
alias diff='colordiff'
alias disapprove='echo ಠ_ಠ'
alias dr-up='sudo ~/Dropbox-Uploader/dropbox_uploader.sh upload'
alias du='du -d 1 -h'
alias floppy='sudo mount -t vfat -o uid=paul,gid=pi /dev/sda /media/floppy-disk/'
alias forkbomb='echo ${bashForkBomb}'
alias get='sudo apt-get install'
alias gh='history | grep'
alias google='w3m google.com'
alias h='history'
alias html='sudo python /home/paul/Programming/python/makeHTML.py'
# IRC client was 'irssi', 'weechat-curses'
alias irc='weechat'
alias konami='echo up, up, down, down, left, right, left, right, B, A, Start'
alias l='ls -lh'
alias la='ls -A'
alias lal='ls -alh'
alias len='Length'
alias length='Length'
# list only directories in the current folder
# from http://www.reddit.com/r/linux4noobs/comments/2hqdq1/i_uploaded_some_scripts_that_just_make_a_gnulinux/ckw0jli
alias ll='ls -lh'
alias lll='ls -alh'
alias LOST='PS1="${GREEN}>: "'
alias lsd='ls -ld */'
alias matlab='sudo octave'
alias mcd='mkdircd'
alias myip='curl http://ifconfig.me/ip'
alias myip2='GetMyIP'
alias myip3='curl https://shtuff.it/myip/short/'
alias myip4='curl icanhazip.com'
alias nano='vim'
alias nethack='telnet nethack.alt.org'
# via http://stackoverflow.com/questions/3001177/how-do-i-grep-for-all-non-ascii-characters-in-unix
alias non-ascii='grep --color='auto' -P -n "[\x80-\xFF]"'
alias noop=':'
alias nop=':'
alias nyan='telnet -e ^c nyancat.dakko.us'
alias nyay='echo Ññ'
alias octave='sudo octave'
# or openports: netstat -tuln
alias pico='vim'
alias please='sudo'
alias ports='netstat -tulanp'
alias prime='IsNumberPrime'
alias python='python3'
alias q='exit'
alias qod='QuoteOfTheDay'
alias quit='exit'
alias quote='QuoteOfTheDay'
alias r='sudo R'
alias R='sudo R'
alias reboot='sudo reboot'
# alternative: reload = '. ~/.bashrc'
alias reload='. /home/paul/.bashrc'
alias remove='sudo apt-get --purge remove'
alias rfk='robotfindskitten'
alias root='sudo -i'
# attempting sudo !! aliased: sudo !! or sudo !-1 have not worked...
alias s='sudo "$BASH" -c "$(history -p !!)"'
alias sl='sl -ael'
# see http://scribblebound.com/2014-02-22.html
alias snake='telnet telnet.bitlag.net'
alias sprunge='curl -F '"'"'sprunge=<-'"'"' http://sprunge.us'
# escape character is x (not CTRL+X)
alias starwars='telnet -e x towel.blinkenlights.nl'
alias sts='aws sts get-caller-identity'
alias su='sudo -i'
alias u='uptime && users'
alias unmount='umount'
alias update='sudo apt-get update && sudo apt-get upgrade'
alias usb='sudo mount -t vfat -o uid=paul,gid=pi /dev/sda /media/usbstick/'
alias usb1='sudo mount -t vfat -o uid=paul,gid=pi /dev/sda1 /media/usbstick/'
alias usb2='sudo mount -t vfat -o uid=paul,gid=pi /dev/sda2 /media/usbstick/'
# since I often forget these:
alias version='uname -a && echo " " && lsb_release -a'
alias vi='vim'
alias website='pushd /var/www'
alias what='PS1="${CYAN}what? ${GRAY}"'
alias why='python2 /home/paul/Programming/python/why/why.py'
alias why?='python2 /home/paul/Programming/python/why/why.py'
# learn more and download wego from github.com/schachmat/wego
alias weather='/home/paul/Programming/Go/wego/bin/wego'
alias wego='/home/paul/Programming/Go/wego/bin/wego'
alias words='cat /usr/share/dict/american-english-insane'
alias x='exit'
alias xyzzy='echo Cheater.'
alias y='yes'
alias zzz='echo $1'


